#!/bin/bash

CURRENT_LAYOUT=$(setxkbmap -query | grep layout | awk '{print $2}')

if [ "$CURRENT_LAYOUT" = "real-prog-qwerty" ]; then
    setxkbmap -layout us
else
    setxkbmap -layout real-prog-qwerty
fi

