#!/usr/bin/env bash

script_dir="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
dry="0"

if [ -z "$XDG_CONFIG_HOME" ]; then
    echo "no xdg config home"
    echo "using ~/.config"
    XDG_CONFIG_HOME=$HOME/.config
fi

if [ -z "$DEV_ENV" ]; then
    echo "env var DEV_ENV needs to be present"
    exit 1
fi

while [[ $# > 0 ]]; do
    if [[ "$1" == "--dry" ]]; then
        dry="1"
    fi
    shift
done

log() {
    if [[ $dry == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
    log "execute: $@"
    if [[ $dry == "1" ]]; then
        return
    fi

    "$@"
}

log "--------- dev-env ---------"

cd $script_dir
copy_dir() {
    pushd $1
    to=$2
    dirs=$(find . -maxdepth 1 -mindepth 1 -type d)
    for dir in $dirs; do
        execute rm -rf $to/$dir
        execute cp -r $dir $to/$dir
    done
    popd
}

copy_file() {
    from=$1
    to=$2
    name=$(basename $from)
    execute sudo rm $to/$name
    execute sudo cp $from $to/$name
}

copy_file $DEV_ENV/background.jpg $HOME/Pictures
copy_dir $DEV_ENV/.config $XDG_CONFIG_HOME
copy_file $DEV_ENV/starship.toml $XDG_CONFIG_HOME
copy_dir $DEV_ENV/.local $HOME/.local
copy_file $DEV_ENV/.bashrc $HOME
copy_file $DEV_ENV/.ready-tmux $HOME
copy_file $DEV_ENV/real-prog-qwerty /usr/share/X11/xkb/symbols/

log "--------- dev-env finished ---------"
