#!/usr/bin/env bash
if [ ! -d $HOME/personal/neovim ]; then
    git clone https://github.com/neovim/neovim.git $HOME/personal/neovim
fi

sudo dnf install cmake gettext lua5.1 liblua5.1-0-dev

cd $HOME/personal/neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install


